# User config
author: "Triply.kr"
tagline: "Pineapple Certfied Jekyll Theme"
description: "여행 블로거<br/>✨️ #여행 #여행스타그램 #여행블로거"
keywords: "여행지 정보 공유, 여행후기"

email: "triply.kr@gmail.com"
instagram: "https://www.instagram.com/triplykr/"

# Site config
baseurl: ""  # 슬래시 포함
url: "https://triply.kr"

# Build settings
markdown:       kramdown
highlighter:    rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

timezone: UTC

# 추가 포스트 설정
collections:
  seminars:
    output: true

sass:
  sass_dir: _sass
  style: compressed

  
# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji
  - jekyll-spaceship

paginate: 6  # 한 페이지당 프로젝트 수
paginate_path: "/page/:num/"

# Excludes
exclude: [ Gemfile, Gemfile.lock ]

host: "0.0.0.0"
livereload: true
reload_port: 5678
