# User config
title: "Triply.kr"
description: "여행 블로거"
keywords: "여행지 정보 공유, 여행후기"

# User info
author:
  name: "트립플리"
  pic: "/assets/images/triply.png"

# Social
instagram: "triplykr"
email: "triply.kr@gmail.com"

# Site config
baseurl: ""  # 슬래시 포함
url: "https://triply.kr"

# Build settings
markdown:       kramdown
highlighter:    rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

timezone: UTC

# 추가 포스트 설정
collections:
  seminars:
    output: true

sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jemoji
  - jekyll-spaceship

# Excludes
exclude: [ Gemfile, Gemfile.lock ]

host: "0.0.0.0"
livereload: true
reload_port: 5678
